### ISSUE TITLE
Pretrained CMU - Performance

### ISSUE THREAD

**Issue by noboevbo** [ildoonet/tf-pose-estimation#26] opened 2017-12-06 13:43 UTC
Hi,
I've just checked out your OpenPose implementation and it works quiet well. As far as I can see the imlementation of the CMU network is equal to the caffe implementation, thus the net should provide comparable performance when used with the same weights. So I downloaded the pretrained CMU model (which was directly converted from the caffe model?) and tested the net on the provided CMU example images, but the performance is quiet bad compared to the caffe implementation. One example would be https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/media/COCO_val2014_000000000357.jpg where tf-openpose doesn't recognize a skeleton at all. 

Is someone able to achive comparable performance on the openpose exampleimages?

**Comment by ildoonet** [comment] 2017-12-08 02:55
Hello, @noboevbo 

It is a great comment for improving this repo. 👍 

Well, your image have a very small persons. CMU's original model processes images with scaled patches. So they scale up the image like 1.2x, 1.5x, etcs and feed it into the network. 

Currently, this repo have no implementation about scaling, so.. I think that is the main difference.

I have a plan to add this feature near future, please wait for it :)

**Comment by ildoonet** [comment] 2017-12-28 09:11
@madhawav Can you share the test codes for PETS2009 dataset? I can use it to evaluate and possibly make some improvements.

**Comment by ouceduxzk** [comment] 2018-03-05 13:34
I also observed that the cmu pose is as not good as the original caffe model especially in a crowded scene, many small people over there. For the mobilenet_thin model shared, I found it also does not works well on the crowded scene and it is substantially slower due to the many false positive caused   joint association computation, the can be viewed as a flaw of the openpose approach, the cpu joint association heavily relys on the accuracy of the pose estimation

**Comment by madhawav** [comment] 2018-04-08 13:59
@ildoonet 
Sorry for my delay. Actually, I fetched the video as inputs to provided demo scripts. (No separate test code was used)

* `src/run_video.py` of _tf-pose-estimation_ provides me this output - https://drive.google.com/file/d/1X09LDfRorb6OGjyTB6xIfe3f42_W6foE/view?usp=sharing
* Demo program of _CMU Openpose_ provides be this output - https://drive.google.com/file/d/1zvufcBSRBdLunkLgbvvFrSKnMWbIpBPO/view?usp=sharing

**The issue is occasionally we would have joints of different persons connected together as one person.**
1) https://drive.google.com/file/d/1nVAa4Wsli6lVk4-C9Bwd1szwbsFU5zd5/view?usp=sharing
2) https://drive.google.com/file/d/1OGTIJFnilRc8azsdPka7ULqVZgZCXExr/view?usp=sharing

I think the issue is caused by an error in mapping the points generated by the CNN. It would be great if this fix can be resolved.

**Comment by ildoonet** [comment] 2018-05-08 05:56
@noboevbo 

![image](https://user-images.githubusercontent.com/1115758/39740290-f39c86f0-52cf-11e8-9890-36e3a9dcde64.png)

Some minor bugs are fixed..

@madhawav 

Thanks for recommending new dataset. I will examine on your dataset as well.

**Comment by ildoonet** [comment] 2018-05-17 04:16
This should be fully resolved in reproduce branch. This will be merged within few weeks.

**Closed by ildoonet** 2018-05-17 04:16 UTC
Labels: enhancement
